import type { Metadata } from 'next';
import { CookiesProvider } from 'next-client-cookies/server';
import './globals.css';
import Header from './_components/header/header';
import Footer from './_components/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CookiesProvider>
          <div className={'layout'}>
            <Header />
            <main className={'content'}>{children}</main>
            <Footer />
          </div>
        </CookiesProvider>
      </body>
    </html>
  );
}
