import type { Metadata } from 'next';

import './globals.css';
import Header from './_components/header/header';
import Footer from './_components/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={'layout'}>
          <Header />
          <main className={'content'}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
